### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by PieBru** [AndrewVeee/nucleo-ai#17]
Hi, nice tool!
The installation went flawlessly.
I then tried the "Research" stream and it returns the error `AttributeError: 'NoneType' object has no attribute 'split'`.

Here is the bash console log, up to just before my query:
```
(base) 18:20:26 piero@gl753vd  nucleo-ai $ ./start.sh 
Fri Mar  8 18:20:35 2024 * Loading modules
[Fri Mar  8 18:20:38 2024] * Loading config
[Fri Mar  8 18:20:38 2024] * Initializing database
[Fri Mar  8 18:20:38 2024] * Initializing RAG
[Fri Mar  8 18:20:40 2024] * Initializing webserver
[Fri Mar  8 18:20:40 2024] * Loading LLM
[Fri Mar  8 18:20:40 2024]   http://192.168.111.181:14434/v1 [key len=4] [model=mistral]
[Fri Mar  8 18:20:40 2024] * Starting job queue
[Fri Mar  8 18:20:40 2024] * Loading functions
[Fri Mar  8 18:20:40 2024]   Secretary: to do lists - ['add_todo']
[Fri Mar  8 18:20:40 2024]   Writer: responses, write docs - ['respond_user', 'create_doc']
[Fri Mar  8 18:20:40 2024]   Artist: take photos, draw, edit media - []
[Fri Mar  8 18:20:40 2024]   Researcher: find, research, look ups, web searches - ['web_search']
[Fri Mar  8 18:20:40 2024]   General: tasks not handled - []
[Fri Mar  8 18:20:40 2024] * Loading Models
[Fri Mar  8 18:20:40 2024]   Models: ['chat', 'assistant-orig', 'assistant', 'message', 'researcher', 'hi']
[Fri Mar  8 18:20:40 2024] * Starting!
 * Serving Flask app 'app.web_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:4742
Press CTRL+C to quit
127.0.0.1 - - [08/Mar/2024 18:20:57] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [08/Mar/2024 18:20:57] "GET /index.html HTTP/1.1" 304 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api//store/list HTTP/1.1" 308 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api//store/list HTTP/1.1" 308 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api//store/list HTTP/1.1" 308 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api//store/list HTTP/1.1" 308 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api//state/check_auth HTTP/1.1" 308 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "GET /icons/help.svg HTTP/1.1" 304 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "GET /icons/moon.svg HTTP/1.1" 304 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "GET /icons/settings.svg HTTP/1.1" 304 -
[Fri Mar  8 18:20:58 2024] SELECT: select * from user_store where data_type=? order by created_at desc [['todo']]
[Fri Mar  8 18:20:58 2024] SELECT: select id, user_id, data_type, subtype, root_id, parent_type, parent_id, name, metadata, pinned, source, embed_model, ai_created, created_at, updated_at from user_store where data_type=? order by created_at desc [['doc']]
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api/store/list HTTP/1.1" 200 -
[Fri Mar  8 18:20:58 2024] SELECT: select * from user_store where data_type=? order by created_at desc [['stream']]
[Fri Mar  8 18:20:58 2024] SELECT: select * from user_store where data_type=? order by created_at desc [['chat']]
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api/store/list HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api/store/list HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api/state/check_auth HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2024 18:20:58] "POST /api/store/list HTTP/1.1" 200 -
```

This the log after my query `List 5 supplements to improve Insulin Resistance.` :
```
127.0.0.1 - - [08/Mar/2024 18:23:44] "POST /api//v1/chat/completions HTTP/1.1" 308 -
127.0.0.1 - - [08/Mar/2024 18:23:44] "GET /icons/loader.svg HTTP/1.1" 304 -
[Fri Mar  8 18:23:44 2024] Using model: researcher ({'topic': 'List 5 supplements to improve Insulin Resistance.'})
[Fri Mar  8 18:23:44 2024] [Researcher:run_llm] [{'role': 'system', 'content': 'You are an advanced topic researcher. Given this topic:\n```\nList 5 supplements to improve Insulin Resistance.\n```\n\nList the 3-7 main research topics for the text. Keep them short.'}]
Job Exception: Connection error.
Exception in thread Thread-23 (handler):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/nucleo-ai/backend/app/ai_models/researcher_model.py", line 305, in handler
    tq.queue.append(self.generate_block("\n".join(chain.parse_list(job.result, None))))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/nucleo-ai/backend/ai_tools/prompt_chain/chain.py", line 12, in parse_list
    for line in output.split("\n"):
                ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

Thank you,
Piero

**Comment by PieBru** [comment]
Got it, there was a typo in the URL of my ollama server, the port is 11434 instead of 14434.
The console error didn't help me, so I would recommend to give meaningful errors for the most common problems, starting with network/server issues.
I leave to you to close this issue.

BTW, your app gave the correct answers.
Thank you much, that tool is impressive!
Piero
